# Generated by Django 3.0.2 on 2020-10-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201001_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ID_NO',
            field=models.CharField(max_length=7),
        ),
    ]
