# Generated by Django 3.0.2 on 2020-09-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200904_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='present_cls',
            new_name='presents_cls',
        ),
    ]
