# Generated by Django 3.0.2 on 2020-10-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_uploadbook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadBook',
            new_name='BookUpload',
        ),
    ]
